dist: trusty
sudo: required
language: node_js
node_js:
  - '8'

os:
  - linux
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

jobs:
  include:
    - stage: lint
      script:
        - ng lint
    - stage: test
      script:
        - npm run test:ngx-year-calendar-coverage
        - npm run report-coverage:ngx-year-calendar
    - stage: build & publish showcase
      script:
        - npm run build:showcase
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GH_TOKEN
        local_dir: dist/ngx-year-calendar-showcase
      if: branch = master
    - stage: build & publish ngx-year-calendar
      script:
        - npm run build:ngx-year-calendar
        - npm run publish:ngx-year-calendar
      if: branch = master
